---
- name: "Init user grace"
  user:
    uid:      2068
    user:     "grace"
    groups:   docker
    shell:    "/usr/bin/fish"
    state:    present
    generate_ssh_key:  yes

- name: Update ~/.vimrc for grace
  template:
    src: HOME/.vimrc
    dest: /home/grace
    owner: grace
    group: grace
