---
- name: "Init user grace"
  user:
    uid:      2068
    user:     "grace"
    groups:   docker
    shell:    "/usr/bin/fish"
    state:    present
    generate_ssh_key:  yes

- name: Update ~/.vimrc for grace
  template:
    src: HOME/.vimrc
    dest: /home/grace
    owner: grace
    group: grace

- name: Make fish dir
  file:
    path:   "/home/grace/.config/fish/conf.d"
    state:  directory
    mode:   '0755'
    owner: grace
    group: grace
    recurse:  yes

- name: Autoclean history
  copy:
    src: HOME/.config/fish/conf.d/clear-history.fish
    dest: "/home/grace/.config/fish/conf.d/clear-history.fish"
    owner: grace
    group: grace

# - name: Autoclean history
#   lineinfile:
#     path: '/home/grace/.bash_logout'
#     line: 'history -c'
#     create: yes
#     owner: grace
#     group: grace
