---
- name: "Init user grace"
  user:
    uid:      2068
    user:     "grace"
    shell:    "/usr/bin/fish"
    state:    present
    generate_ssh_key:  yes

- name: "Set user grace group"
  user:
    user:     "grace"
    groups:   "grace"
