---
- name: Make k3s images dir
  file:
    path:   /var/lib/rancher/k3s/agent/images
    state:  directory
    mode:   '0755'
    recurse:  yes

- stat: path="{{ __k3s_binfile }}"
  register: p
- stat: path="{{ __k3s_airgapfile }}"
  register: p2
- stat: path="/etc/iptables.bak"
  register: p3

- name: Download k3s
  get_url:
    url:  "{{ depends.k3s }}"
    dest: "{{ __k3s_binfile }}"
    mode: '755'
  when: p.stat.exists == False

- name: Download k3s airgap
  get_url:
    url:  "{{ depends.k3s_airgap }}"
    dest: "{{ __k3s_airgapfile }}"
    mode: '644'
  when: p2.stat.exists == False

- name: Make k3s dir for grace
  file:
    path:     /home/grace/.kube
    state:    directory
    owner:    grace
    group:    grace
    recurse:  yes

# - debug:
#     msg: |
#       curl -sfL {{ depends.k3s_installer }} | INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="--write-kubeconfig ~/.kube/config --datastore-endpoint {{ k3s_db_endpoint }}" K3S_TOKEN="{{ k3s_token }}" sh -

# - name: Install k3s
#   shell: |
#     curl -sfL {{ depends.k3s_installer }} | sh -
#   when: p.stat.exists == False

# - name: Make k3s dir for grace
#   file:
#     path:     /home/grace/.kube
#     state:    directory
#     owner:    grace
#     group:    grace
#     recurse:  yes

# - name: Setup k3s for grace
#   copy:
#     src: /etc/rancher/k3s/k3s.yaml
#     dest: /home/grace/.kube/config
#     owner: grace
#     group: grace
#     remote_src: yes

# - name: Fix iptables legacy in debian
#   shell: |
#     iptables-save > /etc/iptables.bak;iptables -F;update-alternatives --set iptables /usr/sbin/iptables-legacy > /dev/null;update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy > /dev/null
#   notify:
#     - reboot machine
#   when: p3.stat.exists == False
