---
- name: 文件行内编辑
  lineinfile:

- name: 文件内容替换
  replace:

- name: shell脚本
  shell: |
    sed -i '$a 127.0.1.1       {{ hostname }}' /etc/hosts;echo '{{ hostname }}' > /etc/hostname
  args:
    chdir: "~/"
  # register: swap_exists
  # failed_when: "'Use `pm2 show' not in swap_exists.stdout"
  # loop: "{{ services }}"
