---
- name: Ping
  hosts: all
  remote_user: root
  # environment:
  #   PATH: /home/worker/.local/bin:{{ ansible_env.PATH }}
  vars:
  tasks:
    - ping:
        data: pong
    - debug:
        var:  ansible_distribution_release
    # - debug:
    #     msg:  "{{ lookup('file', '{{ filename }}') }}"
