---
- name: Init root ssh key
  hosts: all
  remote_user: root
  vars:
    target: root
    pub_key: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user:       "{{ target }}"
        state:      present
        exclusive:  yes
        key:        "{{ lookup('file', '{{ pub_key }}') }}"
