---
- name: Init user
  hosts: all
  remote_user: root
  vars:
    target: root
    pub_key: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
  tasks:
  # 密码（只有在命令行输入才执行）
  # 公钥（有就跑）
    - name: Set authorized key taken from file
      authorized_key:
        user:       "{{ target }}"
        state:      present
        exclusive:  yes
        key:        "{{ lookup('file', '{{ pub_key }}') }}"

- name: "Update [ {{ target }} ] password"
  user:
    password: "{{ password }}"
  when: password != "undefined"

- name: "Undefined alert"
  debug:
    msg:  "New password is undefined, command is abort."
  when: result is skipped
