---
# play-book user-ban inv-main/inventories/development/hosts.inv -k -e target=banuser -e pub_key=pubkey
- name: Ban user
  hosts: all
  remote_user: root
  # vars:
  tasks:
    - name: "Disable user [ {{ target }} ]"
      user:
        user:     "{{ target }}"
        shell:    /usr/bin/false
        state:    present

    - name: "Remove user [ {{ target }} ] password"
      user:
        user:     "{{ target }}"
        password: "*"

    - name: "Remove user [ {{ target }} ] group"
      user:
        user:     "{{ target }}"
        groups:   ''

    - name: Remove authorized key for user [ {{ target }} ]
      authorized_key:
        user:       "{{ target }}"
        state:      absent
        exclusive:  yes
        key:        "{{ pub_key }}"
