---
- name: Prepare mount dirs
  file:
    path:   "{{ item.dir }}"
    state:  directory
    mode:   '0755'
  loop: "{{ mounts }}"
  loop_control:
    label: "{{ item.dir }}"

- name: "Mount disk"
  mount:
    path:   "{{ item.dir }}"
    src:    "{{ item.dev }}"
    fstype: "{{ item.fstype }}"
    state:  present
  loop: "{{ mounts }}"
  loop_control:
    label: "{{ item.dir }}"

- name: Remount all
  shell: |
    mount -a

- name: Change mount dir user
  file:
    path:     "{{ item.dir }}"
    state:    directory
    owner:    "{{ item.user }}"
    group:    "{{ item.user }}"
    recurse:  yes
  when: item.user is defined
  loop: "{{ mounts }}"
  loop_control:
    label: "{{ item.dir }}"
