---
# docker 目前采用最新版本
# docker-compose 1.26.*

# 不适合在 ansible 部署方案中移除旧版
# - name: Remove old version
#   apt:
#     name:
#       - docker
#       - docker-engine
#       - docker.io
#     state:  absent

- name: Add tsinghua docker-ce gpg-key
  apt_key:
    url: https://mirrors4.tuna.tsinghua.edu.cn/docker-ce/linux/debian/gpg
    state: present

- name: Set apt repository for docker-ce
  apt_repository:
    repo: "deb [arch=amd64] https://mirrors4.tuna.tsinghua.edu.cn/docker-ce/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker-ce
  apt:
    name:
      - docker-ce
    state:  present
    update_cache: yes

- name: Prepare docker config dir
  file:
    path:   /etc/docker
    state:  directory
    mode:   '0755'

- name: Set docker deamon config to enable aliyun image source
  template:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - reload daemon
    - restart docker

- name: Install docker-compose
  get_url:
    url:  "{{ depends.docker_compose }}"
    dest: /usr/local/bin/docker-compose
    mode: '755'

- name: Make docker-compose link
  file:
    src: /usr/local/bin/docker-compose
    dest: /bin/docker-compose
    state:    link

- name: Set root to docker group
  user:
    user:     root
    groups:   docker
    state:    present

# Idiot python
# - name: Pip install docker-compose & docker-py
#   pip:
#     name:
#       - docker-py
#       - docker-compose
