---
# docker 目前采用最新版本
# docker-compose 1.26.*

# 不适合在 ansible 部署方案中移除旧版
# - name: Remove old version
#   apt:
#     name:
#       - docker
#       - docker-engine
#       - docker.io
#     state:  absent

- name: Install docker-ce
  apt:
    name:
      - docker-ce
    state:  present

- name: Prepare docker config dir
  file:
    path:   /etc/docker
    state:  directory
    mode:   '0755'

- name: Set docker deamon config to enable image source
  template:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - reload daemon
    - restart docker

- name: Install docker-compose
  get_url:
    url:  "{{ depends.docker_compose }}"
    dest: /usr/local/bin/docker-compose
    mode: '755'

# - name: Set root to docker group
#   user:
#     user:     root
#     groups:   docker
#     state:    present

# Idiot python
# - name: Pip install docker-compose & docker-py
#   pip:
#     name:
#       - docker-py
#       - docker-compose
