---
# - debug:
#     var:  apt_repos

- name: Change apt source
  shell: |
    sed -i "s@deb.debian.org@{{ apt_repos }}@g" /etc/apt/sources.list;sed -i "s@security.debian.org@{{ apt_repos }}@g" /etc/apt/sources.list
  args:
    chdir: "~/"
  when: apt_repos is defined

- name: Install APTITUDE
  apt:
    name:
      - aptitude
    state:  present

- name: Install foundation apps from apt
  apt:
    name:
      - git
      - tree
      - fish
      - sshpass
      - sudo
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      # - python-pip
    state:  present

# - name: Update pip
#   shell: |
#     pip install --upgrade pip;pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/

- name: Install apps from apt
  apt:
    name:   "{{ apt_install }}"
    state:  present
  when: apt_install is defined
