---
# - debug:
#     var:  apt_repos

- name: Change apt source
  shell: |
    sed -i "s@deb.debian.org@{{ apt_repos }}@g" /etc/apt/sources.list;sed -i "s@security.debian.org@{{ apt_repos }}@g" /etc/apt/sources.list
  args:
    chdir: "~/"
  when: apt_repos is defined

- name: Install foundation apps from apt
  apt:
    name:
      - git
      - tree
      - fish
      - sshpass
      - sudo
      - python-pip
    state:  latest
    update_cache: yes

- name: Install apps from apt
  apt:
    name:   "{{ apt_install }}"
    state:  present
    update_cache: yes
  when: apt_install is defined

- name: Apt upgrade
  apt:
    upgrade: yes

- name: Apt autoremove
  apt:
    autoremove: yes

- name: Apt autoclean
  apt:
    autoclean: yes
