---
- import_playbook: update-apt.yml

- name: Makeup borne server
  hosts: borne
  remote_user: root
  vars:
    apt_install:
      - ansible
  roles:
    - role: network-init
    - role: system-init
