---
# - name: Update servers with common setting
#   import_playbook: makeup-common.yml

- name: Update plane servers
  hosts: plane
  remote_user: root
  environment:
    INSTALL_K3S_SKIP_DOWNLOAD: true
    INSTALL_K3S_EXEC: "--write-kubeconfig ~/.kube/config --datastore-endpoint {{ k3s_db_endpoint }}"
    # K3S_DATASTORE_ENDPOINT: "{{ k3s_db_endpoint }}"
    # K3S_DATASTORE_CERTFILE: "/path/to/client.crt"
    # K3S_DATASTORE_KEYFILE: "/path/to/client.key"
    # INSTALL_K3S_EXEC: --docker --write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666
  vars:
  roles:
    - role: grace-init
