---
# - name: Update servers with common setting
#   import_playbook: makeup-common.yml

- name: Update escort servers
  hosts: escort
  remote_user: root
  vars:
  roles:
    # k3s默认会直接在iptables里接管80端口，所以不再在外部安装nginx做反向代理
    # - role: gateway-actived
    - role: database-actived
