---
- name: Update apt repos
  hosts: all
  remote_user: root
  vars:
  roles:
    - role: apt-repos

- name: Update all apt
  hosts: all
  remote_user: root
  vars:
  tasks:

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Apt upgrade
      apt:
        upgrade: yes

    - name: Apt autoremove
      apt:
        autoremove: yes

    - name: Apt autoclean
      apt:
        autoclean: yes
