---
- include: set-root.yml
  tags: set-root
- include: set-user.yml
  tags: set-user
- include: set-profile.yml
  tags: set-profile
- include: setup-koi.yml
  tags: setup-koi
- include: ban-user.yml
  tags: ban-user
