---
- name: "Init users"
  user:
    # uid:      1045
    user:     "{{ item.name }}"
    shell:    "{{ item.shell | default('/usr/bin/fish') }}"
    state:    present
    generate_ssh_key:  yes
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: "Set users password"
  user:
    user:     "{{ item.name }}"
    password: "{{ item.pass }}"
  when: item.pass is defined
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: "Set users group"
  user:
    user:     "{{ item.name }}"
    groups:   "{{ item.groups }}"
  when: item.groups is defined
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Add authorized key for users
  authorized_key:
    user:       "{{ item.name }}"
    state:      present
    key:        "{{ item.pubkey }}"
  when: item.pubkey is defined
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Set sudo
  shell: |
    echo '{{ item.name }} ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/{{ item.name }}
  when: item.sudo is defined and item.sudo == "yes"
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
