---
- name: "Disable user [ {{ target }} ]"
  user:
    user:     "{{ target }}"
    shell:    /usr/bin/false
    state:    present

- name: "Remove user [ {{ target }} ] password"
  user:
    user:     "{{ target }}"
    password: "*"

- name: "Remove user [ {{ target }} ] group"
  user:
    user:     "{{ target }}"
    groups:   ''

- name: Remove authorized key for user [ {{ target }} ]
  authorized_key:
    user:       "{{ target }}"
    state:      absent
    exclusive:  yes
    key:        "{{ pub_key }}"
