---
- include: base-settings.yml
  tags: base-settings
- include: setup-docker.yml
  tags: setup-docker


## Install `docker` and `docker-compose`

```sh
setup-docker
```

ashe user init


## Create `ashe`

```sh
sudo useradd -m ashe
sudo chsh ashe -s /usr/bin/fish
sudo usermod -a -G docker ashe
```

**以下切换到ashe执行**

### Create SSH-Key

```sh
ssh-keygen # 一路回车
```

### Install `omf`

```sh
curl -sfL https://gitee.com/andares/installers/raw/master/fish/install-omf | fish
```

## Mount data disk

如果有数据盘，则挂载到/opt下的某个目录下

### 未初始化磁盘先如下操作

[磁盘挂载后初始化](https://support.huaweicloud.com/qs-evs/evs_01_0034.html)

### 初始化好的磁盘

1. 通过`sudo lsblk`确定设备名，例如`vdb1`
1. 通过`koi mount-disk <dev> <target> <user`进行永久挂载

> Example: `koi mount-disk vdb1 /opt/data01 ashe`
