---
- name: Prepare mount dirs
  file:
    path:   "{{ item.dir }}"
    state:  directory
    mode:   '0755'
    owner:  ashe
    group:  ashe
  loop: "{{ mounts }}"
  when: mounts

- name: "Mount disk"
  mount:
    path:   "{{ item.dir }}"
    src:    "{{ item.dev }}"
    fstype: "{{ item.fstype }}"
    state:  present
  loop: "{{ mounts }}"
  when: mounts