---
- name: Make postgres dir
  file:
    path:   "{{ postgres_dir }}"
    state:  directory
    mode:   '0755'

- name: Make postgres data dir
  file:
    path:   "{{ postgres_dir }}/data"
    state:  directory

- name: Make postgres initdb dir
  file:
    path:   "{{ postgres_dir }}/docker-entrypoint-initdb.d"
    state:  directory

- name: Build docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ postgres_dir }}/docker-compose.yml"

- name: Build brilliant
  template:
    src: "docker-entrypoint-initdb.d/brilliant.sql"
    dest: "{{ postgres_dir }}/docker-entrypoint-initdb.d/brilliant.sql"
  when: brilliant_pass is defined


# TODO: 这里启动pgs存在问题
# - name: Startup postgres
  # docker_service:
  #   project_src: "{{ postgres_dir }}"
  # register: output

  # shell: |
  #   docker-compose up -d
  # args:
  #   chdir: "{{ postgres_dir }}"
