---
- name: Update password
  remote_user: root
  vars:
    target:   root
    password: "undefined"
  tasks:
    - name: "Update [ {{ target }} ] password"
      user:
        password: "{{ password }}"
      when: password != "undefined"

    - name: "Undefined alert"
      debug:
        msg:  "New password is undefined, command is abort."
      when: result is skipped
